### ISSUE TITLE
Add TDM 16 ch Tx only

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/fwk_io#72]
The initial TDM implementation will be:

16 ch TX only
48 kHz audio
32b word size
I2S TDM slave
BCLK is assumed to be integer multiple of our PDM MCLK
BCLK is external
BCLK sampling rising or falling edge TBD
FSYNC offset / data alignment TBD (@Andrew Cavanaugh  getting answer)
FSYNC Length (we only care about edge but TBD just to know).
Target example app with 1 tile 16 mic → 16ch TDM output

See: https://xmosjira.atlassian.net/wiki/spaces/SDK/pages/3811835928/Development+Notes

**Comment by ed-xmos** [comment]
https://xmosjira.atlassian.net/browse/AP-10
