### ISSUE TITLE
TDM large channel count extension

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/fwk_io#73]
Extend 16 channel Tx with 16 channel Rx.  

See: https://xmosjira.atlassian.net/wiki/spaces/SDK/pages/3811835928/Development+Notes

**Comment by ed-xmos** [comment]
https://xmosjira.atlassian.net/issues/?jql=project+%3D+%22AP%22+AND+text+%7E+%22Tdm%22+ORDER+BY+created+DESC&atlOrigin=eyJpIjoiMDcyNWZkMjYwOWVjNGI0YThjM2MwZjUyYzE0NGNjOWMiLCJwIjoiaiJ9
