### ISSUE TITLE
Generate sample app for mic aggregator

### ISSUE THREAD

**Issue by ed-xmos** [xmos/fwk_io#76]
16 channel mic array to TDM16 slave Tx using new libs

Dependent on:
https://github.com/xmos/lib_mic_array/issues/194
and
https://github.com/xmos/fwk_io/issues/72

**Comment by mbanth** [comment]
@ed-xmos, please provide a Story Point value for this issue.  Thanks.

**Comment by ed-xmos** [comment]
The spec and general info page for this can be found here: https://xmosjira.atlassian.net/wiki/spaces/SDK/pages/3837919233/Mic+Aggregator+App

**Comment by ed-xmos** [comment]
https://xmosjira.atlassian.net/browse/AP-11?atlOrigin=eyJpIjoiMGQ3ZTAxNGU4YTA2NDgyNjlhMDRiNjM2Nzc1NWYxMGIiLCJwIjoiaiJ9
