### ISSUE TITLE
TDM16 Tx slave can lock up causing the task to be unresponsive

### ISSUE THREAD

**Issue by ed-xmos** [xmos/fwk_io#77]
See https://xmosjira.atlassian.net/wiki/spaces/SDK/pages/3839328262/TDM16+Slave+Tx+lockup+bug for details.

There may be timing issues on the GPIO however the component should never lock up - only slip. This is a critical bug that needs fixing.

**Comment by mbanth** [comment]
@ed-xmos, please provide a Story Point value for this issue.  Thanks.

**Comment by ed-xmos** [comment]
https://xmosjira.atlassian.net/issues/?jql=project+%3D+%22AP%22+AND+text+%7E+%22Tdm%22+ORDER+BY+created+DESC&atlOrigin=eyJpIjoiMDcyNWZkMjYwOWVjNGI0YThjM2MwZjUyYzE0NGNjOWMiLCJwIjoiaiJ9
